---
all:
  vars:
    ansible_user: gws
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_gws_homelab
    ansible_python_interpreter: /usr/bin/python3

  children:
    rpis:
      hosts:
        rpi3:
          ansible_host: 192.168.1.145
          mac_address: "b8:27:eb:7c:73:db"
          device_info: "Raspberry Pi 3 B+ (906 MiB RAM)"

    x86:
      hosts:
        optiplex:
          ansible_host: 192.168.1.150
          device_info: "Dell OptiPlex 3040 Micro (i5-6500T, 6GB RAM, 240GB SSD)"
