---
all:
  vars:
    ansible_user: gws
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_gws_homelab
    ansible_python_interpreter: /usr/bin/python3

  children:
    services:
      hosts:
        uptime_kuma:
          ansible_host: uptime-kuma.internal
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    routers:
      hosts:
        mikrotik:
          ansible_host: 192.168.10.1   # post-config management IP; for first bootstrap run: -e ansible_host=192.168.88.1
          ansible_connection: local

    rpis:
      hosts:
        rpi3:
          ansible_host: 192.168.10.10
          mac_address: "b8:27:eb:7c:73:db"
          device_info: "Raspberry Pi 3 B+ (906 MiB RAM)"

    x86:
      hosts:
        optiplex:
          ansible_host: 192.168.10.20
          device_info: "Dell OptiPlex 3040 Micro (i5-6500T, 6GB RAM, 240GB SSD)"

        openclaw:
          ansible_host: 192.168.40.30
          mac_address: "94:e6:f7:e5:2e:32"
          device_info: "Lenovo laptop (i5-8265U, 8GB RAM)"

        localllm:
          ansible_host: 192.168.10.30
          mac_address: "c4:5a:b1:fb:17:a1"
          device_info: "Dell OptiPlex Micro Plus 7010 (i7-13700T, 16GB DDR5, 256GB NVMe)"
